Repository kubernetes-sigs/verify-conformance, pull requests merged in 2024-08, with the labels that each got.

#188 chore: add ghproxy to development docs
  docs/development.md
Labels: size/S, approved, cncf-cla: yes

#187 chore: add bot response for non-conf results
  internal/plugin/plugin.go
  internal/plugin/plugin_test.go
Labels: size/M, approved, cncf-cla: yes

#192 Remove Zach from OWNERS file
  OWNERS
Labels: lgtm, size/XS, approved, cncf-cla: yes

#193 chore: update cloudbuild subs, imgs and opts
  cloudbuild.yaml
Labels: lgtm, size/XS, approved, cncf-cla: yes

#194 chore: update to latest ko in cloudbuild
  .ko.yaml
  cloudbuild.yaml
Labels: lgtm, size/XS, approved, cncf-cla: yes

#195 chore: use ko with --bare in cloudbuild
  cloudbuild.yaml
Labels: lgtm, size/XS, approved, cncf-cla: yes

#197 Mention "conformance results for" when !isConformancePR()
  internal/plugin/plugin.go
  internal/plugin/plugin_test.go
Labels: lgtm, size/XS, approved, cncf-cla: yes
